services:
  teslodb:
    image: mongo
    restart: always
    container_name: teslo-db
    ports:
      - 27017:27017
    volumes:
      - ./db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
